version: '3'

networks:
  dockerDev:

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dockerDev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - dockerDev

  mysql:
    image: mysql:5.7
    container_name: dockerDev-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dockerDev

  nginx:
    image: nginx:alpine
    container_name: dockerDev-nginx
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - dockerDev

  redis:
    image: redis:alpine
    container_name: dockerDev-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - dockerDev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: dockerDev-phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - dockerDev
